### ISSUE TITLE
"with Corrections Against Manuscripts."

### ISSUE THREAD

**Issue by kylak** [sleeptillseven/LXX-Swete#1]
Hi, 

When you said "with Corrections Against Manuscripts." you mean that you added manually correction to the First1KGreek data or that the First1KGreek data added correction against the manuscript ?

Thanks.

**Comment by sleeptillseven** [comment]
Hi Kylak,

Sorry need to spend some time and go over the Readme. What I'm doing is that I take the text from 1K and check against scanned manuscripts and correct them if I find mistakes in the text from 1K project. That's why it's so slow, it's a lot of effort.

Best,
Chris

**Comment by kylak** [comment]
Ok, but in that case why not correcting directly the 1K data instead of creating new ones ?

**Comment by jtauber** [comment]
@kylak the two aren't mutually exclusive. We can contribute the corrections back to First1K AND continue to develop this text to serve, amongst other things, the Greek Learner Texts Project.

**Comment by kylak** [comment]
@jtauber So I'm not sure to understand the difference between the text of this repo and the one of First1K. If the text of this repo is the same than the one of First1K, why is "with Corrections Against Manuscripts." added to the Readme ?

**Comment by jtauber** [comment]
It's not exactly the same. @sleeptillseven is correcting mistakes in the First1K text by comparing to the manuscripts.

**Comment by kylak** [comment]
When you say "manuscript" you mean the Vaticanus codex (base text of the LXX-Swete) or a facsimile of the Swete's LXX ?

**Comment by jtauber** [comment]
I'll let @sleeptillseven answer that question :-)

**Comment by kylak** [comment]
But finally I don't understand why "It's not exactly the same."..

**Comment by jtauber** [comment]
> But finally I don't understand why "It's not exactly the same."..

Because there are mistakes in the First1K.

**Comment by sleeptillseven** [comment]
@kylak I'm checking the First1K text against the best available latest edition of Swete's facsimile. Checking against the Codex itself would take just too much. The aim here is to provide:
* a resource for language learners
* a reliable text itself

**Comment by kylak** [comment]
Ok thanks.
